# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\x12\x0cprotobuf.log\"\xda\x01\n\x08LogEntry\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12(\n\x08logLevel\x18\x02 \x01(\x0e\x32\x16.protobuf.log.LogLevel\x12&\n\x07logType\x18\x03 \x01(\x0e\x32\x15.protobuf.log.LogType\x12\x11\n\tsubsystem\x18\x04 \x01(\t\x12\x0c\n\x04size\x18\x05 \x01(\r\x12\x10\n\x08logEntry\x18\x06 \x01(\x0c\x12\x10\n\x08typeinfo\x18\x07 \x01(\t\x12$\n\x03src\x18\x08 \x01(\x0e\x32\x17.protobuf.log.LogSource*-\n\x07LogType\x12\x08\n\x04TEXT\x10\x00\x12\x0c\n\x08PROTOBUF\x10\x01\x12\n\n\x06\x42INARY\x10\x02*4\n\x08LogLevel\x12\x08\n\x04INFO\x10\x00\x12\t\n\x05\x44\x45\x42UG\x10\x01\x12\x08\n\x04WARN\x10\x02\x12\t\n\x05\x45RROR\x10\x03*%\n\tLogSource\x12\x0c\n\x08\x46IRMWARE\x10\x00\x12\n\n\x06\x42RIDGE\x10\x01\x42\x45\n8de.htwk_leipzig.naocontrol.backend.internal.protobuf.logB\tLogProtosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n8de.htwk_leipzig.naocontrol.backend.internal.protobuf.logB\tLogProtos'
  _LOGTYPE._serialized_start=248
  _LOGTYPE._serialized_end=293
  _LOGLEVEL._serialized_start=295
  _LOGLEVEL._serialized_end=347
  _LOGSOURCE._serialized_start=349
  _LOGSOURCE._serialized_end=386
  _LOGENTRY._serialized_start=28
  _LOGENTRY._serialized_end=246
# @@protoc_insertion_point(module_scope)
